### ISSUE TITLE
Make gradlew and gradle executable

### ISSUE THREAD

**Issue by scpeters** [ihmcrobotics/ihmc_ros_core-release#1]
@caguero: I had to add the following lines to my dockerfile when testing the ros-indigo-ros-java-adapter deb:

```
chmod a+x \
    /opt/ros/indigo/share/ihmc_ros_java_adapter/gradlew \
    /opt/ros/indigo/share/ihmc_ros_java_adapter/gradle
```

**Comment by dljsjr** [comment]
`gradle` is a directory, it probably shouldn't be executable.

I just did a fresh clone of ros_core and `gradlew` was executable for user/group/everyone so I'm not sure what's removing that executable bit but it's not us...

**Comment by scpeters** [comment]
I made this a while ago, and I believe @caguero has already fixed the deb, and submitted a fix for this in https://github.com/ihmcrobotics/ihmc_ros_core/pull/4 (installing `gradlew` as a `PROGRAM` I think).

**Comment by dljsjr** [comment]
This PR has been merged so I'll close out this issue.
